### ISSUE TITLE
运行UCLC.ahk 出现两个报错

### ISSUE THREAD

**Issue by Knomo-exe** [zedeeee/UCLC#20]
如下图
1.
![image](https://github.com/user-attachments/assets/fd9dc374-92db-42ac-8a72-b694038443e2)

2.
![image](https://github.com/user-attachments/assets/1fa597e3-f27f-482f-83c2-dd3c1115a224)

**Comment by Knomo-exe** [comment]
另外一个问题反馈： 现在双击Esc  不能删除搜索框里面输错的指令。

**Comment by zedeeee** [comment]
> 另外一个问题反馈： 现在双击Esc 不能删除搜索框里面输错的指令。

托盘图标右键 - 开发功能 - ESC增强（每次载入脚本都需要勾选这个。下一个版本将默认开启这个功能）

**Comment by zedeeee** [comment]
> 如下图 1. ![image](https://private-user-images.githubusercontent.com/72645050/352831753-fd9dc374-92db-42ac-8a72-b694038443e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODQ5OTUsIm5iZiI6MTcyMjE4NDY5NSwicGF0aCI6Ii83MjY0NTA1MC8zNTI4MzE3NTMtZmQ5ZGMzNzQtOTJkYi00MmFjLThhNzItYjY5NDAzODQ0M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE2MzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTQ5ZGQ0YjNkNDdjOTM1YmI2ZDk1YmNjZTU0ODM0ZWRlMmUzYmNlMmYzODAwMzkxMDcyOGVmNzg1NTUzNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1thr3SuiKg0OqDcFocz9BBf_Kbg1RX9Ds--6b7eMgnw)
> 
> 
> ![image](https://private-user-images.githubusercontent.com/72645050/352831853-1fa597e3-f27f-482f-83c2-dd3c1115a224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODQ5OTUsIm5iZiI6MTcyMjE4NDY5NSwicGF0aCI6Ii83MjY0NTA1MC8zNTI4MzE4NTMtMWZhNTk3ZTMtZjI3Zi00ODJmLTgzYzItZGQzYzExMTVhMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE2MzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhY2ZkNjMyZTU4NTc1M2JhODMzYWZhMmQxYmVmMmM0MzllODNkZDNjZTgxMjg0YjkyODRkMThiZjlmNjA2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._bqibVLILMe_YpFN5IdNrwaBo5tjdIHUzm1ugBFv_oo)

看起来像是配置文件读取的问题
先参考这个[链接](https://github.com/zedeeee/UCLC-config/blob/master/README.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E7%BB%93%E6%9E%84)检查配置文件里的内容

**Comment by Knomo-exe** [comment]
配置文件的读取问题  如下图：
![image](https://github.com/user-attachments/assets/9ed34021-405d-403f-8969-1465a5a9c152)

这两个报错分别位于
UCLC-2.4.1==>UCLC.ahk 文件的第37行  ;
 UCLC-2.4.1==>Lib==>CAT_Automatic.ahk 文件的第244行 ;
请作者检查下这两行代码是否有问题

**Comment by zedeeee** [comment]
> 配置文件的读取问题  如下图：
> ![image](https://github.com/user-attachments/assets/9ed34021-405d-403f-8969-1465a5a9c152)
> 
> 这两个报错分别位于
> UCLC-2.4.1==>UCLC.ahk 文件的第37行  ;
>  UCLC-2.4.1==>Lib==>CAT_Automatic.ahk 文件的第244行 ;
> 请作者检查下这两行代码是否有问题

执行什么操作的时候出现的？快捷键和别名的配置能否贴出来？

**Comment by Knomo-exe** [comment]
1.双击运行UCLC.ahk 出现的，运行详情请见下方视频：

https://github.com/user-attachments/assets/75089c31-c170-4b9a-be98-73915621fc48

2.快捷键配置文件请见下方压缩包：
[CAT_Alias.zip](https://github.com/user-attachments/files/16414475/CAT_Alias.zip)

**Comment by zedeeee** [comment]
从 v2.4.0 开始，CATIA 的配置文件 `CAT_Alias.ini` 被拆分成两部分：命令别名保持不变，而热键部分移动到了新的配置文件 `CAT_Hotkey.ini` 中。相较于之前将两者混在一起的方案，改进后的方案更为清晰，用户别名和热键精准区分工作台。

### 解决方案如下：

1. [下载](https://github.com/zedeeee/UCLC-config)最新的配置文件模板到 `UCLC/user-config` 目录。
2. 分别添加自己的用户别名到 `CAT_Alias.ini` 文件中，热键添加到 `CAT_Hotkey.ini` 文件中。
3. 查看[文档](https://github.com/zedeeee/UCLC-config/blob/master/README.md)以获得详细的修改配置文件的指导。

**Comment by Knomo-exe** [comment]
问题已解决！谢谢作者，我添加了CAT_Hotkey.ini文件后就不会报错了，说明这两个配置文件缺一不可。

作者的思路很好，将用户别名和快捷键分开。但是有几个问题还是想向作者请教一下：

1. 别名和热键 他们的本质有什么不同，是一个用字母实现，一个用组合键实现吗？
2. 两种方式控制范围有没有区别，都可以定义<工作间呈式>的所有命令吗？
    我刚试了一下，两种配置都可以完成同一种指令：
    如<隐藏/显示>功能我在<CAT_Alias.ini>设置的是<`>键，在CAT_Hotkey.ini中设置的是<!1>，两种快捷命令都可以实现此功能。

感谢作者。

**Comment by zedeeee** [comment]
恭喜恭喜

1. 别名需要用到终止符（回车）来表示输入完毕并执行命令，而热键不需要。（目前阶段在热键里配置单字母可以实现类似P1的单键快捷键，后续会优化一些小问题）
2. 控制范围没有区别，只是两种调用方式而已

**Comment by Knomo-exe** [comment]
好的，再次感谢！❤️
