### ISSUE TITLE
如何创建自己的快捷键

### ISSUE THREAD

**Issue by Knomo-exe** [zedeeee/UCLC#8]
是按照自己的习惯在catia里面将快捷键设置好了，然后在CATAlias.ini里面填写对应的快捷键吗？可否出个教程？
因为我是第一次接触UCLC，我觉得作者的项目很好，我想知道具体做法，如何与您取得联系？

**Comment by Knomo-exe** [comment]
我现在的做法是 将config.ini文件复制到user-config文件夹里，然后将[Alias.ini]里面的命令复制进去了，如图所示。
![PixPin_2024-04-25_19-28-59](https://github.com/zedeeee/UCLC/assets/72645050/7ecd38f5-5fec-4e70-a40d-cf56ae0a5320)
![PixPin_2024-04-25_19-29-25](https://github.com/zedeeee/UCLC/assets/72645050/ce4bd1ed-d44c-4200-aaca-6c7c6264a695)



我使用的时候某些命令显示 “没有找到对应的命令”，然后草图编辑器中D约束 我希望是直接标注尺寸的快捷键，但使用的时候弹出来的是约束定义，所以我想修改，但又不知道如何修改。

**Comment by zedeeee** [comment]
配置文件[自定义方法](https://github.com/zedeeee/UCLC-config?tab=readme-ov-file#%E8%87%AA%E5%AE%9A%E4%B9%89)已更新，如果您还遇到任何问题，请随时与我联系

**Comment by Knomo-exe** [comment]
太感谢了，按照您更新的使用说明，我切换工作台导出相应的工作间呈式，然后测试了一下，成功了。

还有几个问题想向您请教:

1. **工作台指令：**

我注意到您在配置文件的示例中定义了如下的指令：
[工作台]
2001=零件设计
2002=装配设计
2003=草图编辑器
3006=创成式外形设计
2009=工程制图
2019=Generative Sheetmetal Design

‘=’ 前面的数字是快速切换不同的工作台时使用的吗？我刚刚尝试了一下，如输入2001，然后按下space，没有成功。
所以如果这些是快捷指令的话，我想请教一下这些工作台指令的具体用法。

**2.Esc的使用习惯：**

之前使用catia建模的习惯，当我点选某个命令发现选错不想用时，通常我会按下Esc来取消。

在使用UCLC输入快捷指令并按下space后，若想取消，此时按Esc是不起作用的，例如我在按下D（约束）+space后，若想取消命令，此时按Esc是无效的，我必须先把尺寸标注出来，然后删掉。我知道您最近开发出了一个新功能，定义了Esc是清空输入栏（这样也很方便清空指令）。

所以我想知道您是如何快速取消已经生效的快捷指令的。

再次感谢作者的帮助！

**Comment by zedeeee** [comment]
很高兴您能够顺利使用这个脚本工具！
1. 关于`[工作台]`section，前面的数字并不是快捷键，只是用工作台的标识而已。如果想要通过快捷键切换工作台，可以尝试通过CATIA菜单栏“工具-自定义-开始菜单”来设置。
2. ESC这个属于是BUG了，在我的使用经历中，有一定几率会导致不能取消当前执行的命令。如果这造成困扰，可以将`config.ini`配置文件里的对应部分作如下修改来禁用这个功能。当然我也会争取早日修复这个问题，我挺喜欢这个功能的。
```ini
[DevFunc]
ESC_CLEAN = 0
```

**Comment by Knomo-exe** [comment]
明白了！Esc这个功能在使用快捷命令时非常好用，如果它同时也能取消当前执行的快捷指令就更好了。😄

另外，附加功能里的 **产品结构树自动排序** 是按照什么规则进行自动排序的？
如产品结构树中，产品和产品排在一起、零件和零件排在一起，然后各自按照名称进行自动排序？

**Comment by zedeeee** [comment]
**是按照结构树上的零件名称自动排序**
别名配置如下：
```ini
[装配设计]
Custom_User_Alias = CATPstReorderHdr &cat_auto_graph_tree_reorder
```
`Custom_User_Alias`可修改成自己喜好的别名

**CATIA中也要做相应修改，以确保排序成功实现**
`工具 - 选项 - 基础结构 - 产品结构 - 节点自定义 - 自定义显示 - 配置` ，确保至少定义了零件编号（#PN#）、实例名称（#IN#）节点
```
#PN#__#IN#
```

**Comment by Knomo-exe** [comment]
好的，谢谢作者。
